dicoroles = {
    'Confesseur': 5,
    'Cupidon': 6,
    'Salvateur': 7,
    'LG': 8,
    'GML': 8,
    'LGA': 8,
    'PF': 9,
    'IPDL': 10,
    'LGB': 11,
    'Voyante': 12,
    'Sorcière': 13,
    'Renard': 14,
    'Corbeau': 15,
    'JDF': 16,
    'Voleur': 17,
    'Soeur': 18,
    'Frère': 19,
    'Chaman': 20,
    'Jaloux': 21,
    'Noctambule': 22,
    'Oeil': 23,
    'Traitre': 24,
    'Imposteur': 25,
    'Enfant': 26,
    'Dictateur': 27,
    'Assassin': 28,
    'Devin': 29
}

trad_roles = {
    'LG': 'Loup-Garou',
    'LGA': 'Loup-Garou Anonyme',
    'LGB': 'Loup-Garou Blanc',
    'IPDL': 'Infect père des loups',
    'JDF': 'Joueur de flûte',
    'Enfant': 'Enfant Sauvage',
    'Chevalier': "Chevalier à l'épée rouillée",
    'Ours': "Montreur d'Ours",
    'Bouc': "Bouc émissaire",
    'Idiot': "Idiot du village",
    'Villageois': 'Simple Villageois',
    'Ange': 'Ange',
    'Sectaire': 'Abominable Sectaire',
    'Juge': 'Juge Bègue',
    'Couple': 'Couple',
    'GML': 'Grand Méchant Loup',
    'PF': 'Petite Fille',
    'Chaperon': 'Chaperon Rouge',
    'Traitre': 'Traître',
    'Oeil': '3ème Oeil',
    'Servante': 'Servante Dévouée',
    'Devin': 'Devin Maléfique'
}

desc_roles = {
    'Voyante': "(VILLAGE) Chaque nuit, le joueur pourra sonder quelqu'un dans la partie pour connaître son rôle. Si la voyante est bavarde, le rôle sera dit publiquement (mais pas le pseudo).",
    'Sorcière': "(VILLAGE) Ce joueur détient deux potions utilisables la nuit, après l'attaque des loups-garous: une de vie, permettant de soigner la personne attaquée par les loups-garous la même nuit et une de mort, permettant de tuer quelqu'un sans qu'il ne puisse être sauvé. Si un membre du couple est touché, alors son confident se suicidera également.",
    'PF': "(VILLAGE) Ce joueur pourra voir la discussion des loups-garous chaque nuit de manière cryptée, mais ne verra pas leurs pseudos.",
    'Renard': "(VILLAGE) Tous les jours, il aura la possibilité de renifler un joueur, si celui-ci ou un de ses deux voisins est loup-garou, le renard recevra l'information comme quoi un des trois joueurs est loup-garou. Mais attention, s'il renifle un joueur et que parmi lui et ses deux voisins ne se trouvent aucun loup-garou, il ne pourra plus flairer jusqu'à la fin de la partie.",
    'Soeur': "(VILLAGE) Elles connaissent mutuellement leurs identités et toutes les nuits, elles pourront parler pendant 30 secondes dans un channel adapté. Il n'y a que deux soeurs dans la partie.",
    'Frère': "(VILLAGE) Ils connaissent mutuellement leurs identités et toutes les nuits, ils pourront parler pendant 30 secondes dans un channel adapté. Il n'y a que trois frères dans la partie.",
    'Salvateur': "(VILLAGE) Chaque nuit avant l'attaque des loups, il pourra protéger une personne de l'attaque des loups-garous. Il devra alors dire au MDJ qui sera protégé. Son pouvoir protège également de l'attaque de l'Assassin.",
    'LG': "(LOUP-GAROU) N'a pas de particularités excepté qu'il peut choisir une victime chaque nuit et qu'il peut voter",
    'IPDL': "(LOUP-GAROU) A un moment dans la partie, il peut infecter une de ses victimes pour le transformer en loup-garou. Le joueur infecté gardera toutefois ses pouvoirs mais sera dans le camp des loups-garous.",
    'LGB': "(SOLO) Une fois toutes les deux nuits, il décidera s'il tue un loup-garou ou non. Le joueur doit gagner seul mais les loups-garous ne connaissent pas son identité.",
    'Cupidon': "(SOLO) Au début de la partie, le cupidon va envoyer un message au MDJ pour unir deux personnes en couple. Ces personnes pourront gagner en couple avec le cupidon ou sans lui s'il advient à mourir. Ils peuvent décider de gagner avec leur camp s'ils sont tous deux du même. Si le couple meurt, il appartient au camp du village.",
    'JDF': "(SOLO)Chaque nuit, ce joueur pourra charmer deux personnes maximum. Son but étant de charmer toutes les personnes présentes dans la partie. S'il advient à toutes les charmer, il a gagné. Les charmés connaissent l'identité de tous les charmés. Etre charmé ne présente aucun inconvénient ni avantage.",
    'Enfant': "(AUTRE) Au début de la partie, il dit au MDJ une personne présente dans la partie. Il débute en tant que villageois. Si la personne choisie vient à mourir, alors l'enfant sauvage passe loup-garou et doit gagner avec eux.",
    'Voleur': "(AUTRE)A la fin de la nuit, il pourra voler le rôle d'une personne de son choix. La personne deviendra donc le rôle volé.",
    'Ancien': "(VILLAGE) Ce joueur a la particularité de survivre à la 1ere attaque des loups-garous envers lui. Par contre, s'il advient à mourir de la main du village (par votes, potion de mort, ...) alors toutes les personnes ayant influencé sa mort perdront leur pouvoirs jusqu'à la fin de la partie.",
    'GML': "(LOUP-GAROU) Tant qu'aucun loup-garou ne meurt, le grand méchant loup pourra choisir une seconde victime à tuer la nuit. Il pourra également choisir une victime chaque nuit comme tout autre loup-garou.",
    'LGA': "(LOUP-GAROU) Chaque nuit, il peut choisir une victime et aura la particularité d'avoir un rôle camouflage (donné par le MDJ) à chaque début de jour qui influenceront les visions ou reniflement de la voyante/monteur d'ours/renard. Le rôle donné pourra être un rôle appartenant au camp des loups-garous.",
    'Ours': "(VILLAGE) Chaque jour, si un ou deux loup(s)-garou(s) est ou sont situé(s) à côté du montreur d'ours, alors le village apprendra que le montreur d'ours a grogné et par conséquent, a un minimum d'un loup-garou à côté de lui. Mais attention, personne ne connait l'identité du montreur d'ours.",
    'Ange': "(SOLO) Son but est de mourir le premier jour par les votes. S'il réussit, la partie et finie et il gagne. S'il échoue, il appartient au camp du village.",
    'Chevalier': "(VILLAGE) S'il advient à mourir par l'attaque de loups-garous la nuit, alors le loup-garou le plus proche de lui (en dessous de lui) va mourir le jour après la mort du chevalier.",
    'Chaman': "(VILLAGE) Il pourra prendre connaissance des informations données par les personnes mortes. Il recevra les messages de ce salon de manière codée, et sans connaître l'auteur du message.",
    'Corbeau': "(VILLAGE) A la fin de la nuit, le corbeau pourra mettre 2 votes sur une personne de son choix jusqu'à la fin du jour (il pourra voter également).",
    'Bouc': "(VILLAGE) En cas d'égalité lors des votes, le bouc-émissaire va mourir instantanément. Dans ce cas, il peut interdire 3 personnes maximum de voter pendant 2 jours.",
    'Idiot': "(VILLAGE) Si l'idiot du village prend la majorité des votes, alors il perdra son droit de vote mais il ne sera pas tué et tout le monde aura prit connaissance de son rôle.",
    'Villageois': "(VILLAGE) N'a pas de particularités excepté qu'il peut voter normalement.",
    'Chasseur': "(VILLAGE) Si ce joueur advient à mourir, alors celui-ci pourra tirer sur un joueur, causant ainsi sa mort (qui est également impossible à contrer). Si un membre du couple est touché, alors son confident se suicidera également.",
    'Sectaire': "(SOLO) Au début de la partie, la moitié de joueurs de la partie vont être sélectionnés aléatoirement. Seul l'abominable sectaire connaît les joueurs sélectionnés. Son but est d'éradiquer toute la liste des joueurs cités au début de la partie. S'il parvient à faire celà, il gagne la partie. Vous recevrez les personnes à éliminer après ce message.",
    'Juge': "(VILLAGE) Une fois dans la partie, le juge bègue peut décider de relancer un second tour de votes. Il y aura alors une autre personne à éliminer en plus du joueur tué précédemment. Vous ferez cette demande par MP avec le MDJ.",
    'Confesseur': "(VILLAGE) A un moment dans la partie, tout comme la voyante, il peut sonder une personne et connaître son rôle. La personne sondée sait alors qui est le confesseur. Vous ferez cette demande par MP au MDJ.",
    'Jaloux': "(VILLAGE) De la même manière que la Petite-fille et le Chaman, le Jaloux recevra les messages du couple de manière cryptée sans connaître les pseudos.",
    'Chaperon': "(VILLAGE) Tant que le Chasseur est en vie, elle ne peut pas se faire tuer par les LG.",
    'Ankou': "(VILLAGE) Après sa mort, il peut encore voter avec le village pendant 2 tours. Il devra contacter le MDJ par MP pour poser son vote",
    'Dictateur': "(VILLAGE) Une seule fois par partie il peut faire un coup d'état, ce qui annulera le vote. Il décide ensuite d'éxécuter une personne du village. Si il ne tue pas un Loup-Garou, il meurt. Sa demande se fait à la fin du vote par MP avec le MDJ (comme le Juge Bègue)",
    'Noctambule': "(VILLAGE) Chaque nuit, il peut rendre visite à un joueur. Ce joueur ne pourra alors pas utiliser ses pouvoirs, mais connaîtra l'identité du Noctambule.",
    'Faucheur': "(VILLAGE) Si il meurt par le vote du Village ou par la sorcière, alors ses deux voisins meurent en même temps que lui.",
    'Oeil': "(VILLAGE) Durant la 1ère nuit et le 1er jour seulement, il reçoit tous les messages de tous les channels de manière cryptée. Il sait de quels channels proviennent les messages. Il connaît également la couverture du LGA, le maître de l'enfant ainsi que le rôle de l'imposteur.",
    'Traitre': "(LOUP-GAROU) Le Traître doit gagner avec les Loups. Au début de la partie, il se vera attribuer un rôle au hasard parmis les rôles VILLAGE. Il ne connaît pas les LG de la partie, et les LG ne le connaissent pas.",
    'Imposteur': "(AUTRE) Au début de la partie il choisit un rôle parmis 2 qui lui sont proposés. Ces deux rôles sont aléatoires parmis tous les rôles NON PRÉSENTS dans la partie.",
    'Servante': "(AUTRE) Une fois dans la partie lorsque qu'une personne meurt par le vote du village, la Servante Dévouée peut dévoiler publiquement son identité. Elle prend alors le rôle de la personne morte sans que personne ne connaisse le rôle de la personne.",
    'Assassin': "(SOLO) Chaque nuit, s'il le veut, il peut tuer un autre villageois au choix. Son but est d'être le dernier survivant. Précisions: il ne peut PAS être tué par les Loups, et sa victime ne peut PAS être sauvée par la Sorcière, MAIS peut être sauvée par le Salvateur.",
    'Devin': "(SOLO) Chaque nuit il recevra le nom d'un joueur. Si il devine le rôle de cette personne, il peut tuer une personne de la même manière que l'Assassin. Sinon son fonctionnement est le même que l'Assassin."
}

chans = {
    0: 'commandes-bot',
    1: 'roles-de-la-game',
    2: 'place-du-village',
    3: 'morts',
    4: 'charmés',
    5: 'confesseur',            
    6: 'cupidon-et-couple',
    7: 'salvateur',
    8: 'loups-garous',
    9: 'petite-fille',
    10: 'infect-père-des-loups',
    11: 'loup-garou-blanc',
    12: 'voyante',
    13: 'sorcière',
    14: 'renard',
    15: 'corbeau',
    16: 'joueur-de-flûte',
    17: 'voleur',
    18: 'soeurs',
    19: 'frères',
    20: 'chaman',
    21: 'jaloux',
    22: 'noctambule',
    23: '3e-oeil',
    24: 'traître',
    25: 'imposteur',
    26: 'enfant-sauvage',
    27: 'dictateur',
    28: 'assassin',
    29: 'devin'
}




